### ISSUE TITLE
Notify slack user about Sams response

### ISSUE THREAD

**Issue by herrbenesch** [voiio/Sam#25]
As a slack user I want to know when my response is ready.

Currently I'm only notified when Sam starts to write an answer. I have no glue on when I'm going to receive an answer.
Ich would be nice if I

- Get notified once the answer is there
- AND / OR the response is streamed as in chat.openai.com

**Comment by codingjoe** [comment]
I do have that change in my local stash… wait let me…

**Comment by herrbenesch** [comment]
🚀 thanks @codingjoe
